@echo off
echo 🎨 ShutUpAndType Local Icon Generation
echo =====================================
echo.

REM Check if Node.js is available
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo ❌ Node.js not found. Please install Node.js first.
    echo    Download from: https://nodejs.org/
    pause
    exit /b 1
)

REM Check if source SVG exists
if not exist "assets\icons\source\microphone.svg" (
    echo ❌ Source SVG not found: assets\icons\source\microphone.svg
    pause
    exit /b 1
)

echo ℹ️  Installing required tools...
npm install -g sharp-cli

REM Create directories
echo ℹ️  Creating output directories...
if not exist "assets\icons\generated" mkdir "assets\icons\generated"
if not exist "assets\icons\ico" mkdir "assets\icons\ico"

echo ℹ️  Generating PNG icons from SVG...

REM Generate all required PNG sizes for normal microphone
for %%s in (16 20 24 32 40 48 64 96 128 256 512) do (
    echo Generating normal microphone %%sx%%s...
    npx sharp --input "assets\icons\source\microphone.svg" --output "assets\icons\generated\microphone-%%sx%%s.png" resize %%s %%s --format png
)

REM Generate all required PNG sizes for recording microphone (if source exists)
if exist "assets\icons\source\microphone-recording.svg" (
    echo ℹ️  Generating recording variant PNG icons...
    for %%s in (16 20 24 32 40 48 64 96 128 256 512) do (
        echo Generating recording microphone %%sx%%s...
        npx sharp --input "assets\icons\source\microphone-recording.svg" --output "assets\icons\generated\microphone-recording-%%sx%%s.png" resize %%s %%s --format png
    )
) else (
    echo ⚠️  Recording SVG not found, skipping recording variant
)

echo ✅ PNG generation complete!

REM Check if ImageMagick is available for ICO generation
where magick >nul 2>nul
if %errorlevel% neq 0 (
    echo ⚠️  ImageMagick not found. Cannot generate ICO files.
    echo    ICO files will be generated by CI workflow.
    echo    To generate locally, install ImageMagick from: https://imagemagick.org/
) else (
    echo ℹ️  Generating ICO files...

    REM Main application icon
    magick convert "assets\icons\generated\microphone-16x16.png" "assets\icons\generated\microphone-32x32.png" "assets\icons\generated\microphone-48x48.png" "assets\icons\generated\microphone-256x256.png" "assets\icons\ico\microphone.ico"

    REM System tray icon
    magick convert "assets\icons\generated\microphone-16x16.png" "assets\icons\generated\microphone-20x20.png" "assets\icons\generated\microphone-24x24.png" "assets\icons\generated\microphone-32x32.png" "assets\icons\ico\microphone-tray.ico"

    REM Recording system tray icon (if recording PNGs exist)
    if exist "assets\icons\generated\microphone-recording-16x16.png" (
        echo Generating recording tray icon...
        magick convert "assets\icons\generated\microphone-recording-16x16.png" "assets\icons\generated\microphone-recording-20x20.png" "assets\icons\generated\microphone-recording-24x24.png" "assets\icons\generated\microphone-recording-32x32.png" "assets\icons\ico\microphone-recording-tray.ico"
    )

    REM Copy main icon to root
    copy "assets\icons\ico\microphone.ico" "microphone.ico" >nul

    echo ✅ ICO generation complete!
)

echo.
echo 🎉 Icon generation finished!
echo.
echo Generated files:
echo   📁 assets\icons\generated\ - PNG files
if exist "assets\icons\ico\microphone.ico" (
    echo   📁 assets\icons\ico\ - ICO files
    echo   📄 microphone.ico - Main application icon
)

echo.
echo 💡 To validate icons, run: .\scripts\validate-icons.ps1
echo.
pause